export const mockDBBidBuyResponseNoBid = {
    'dealerBlockAuction': {
        'auctionStartTime': 2234567,
        'auctionEndTime': 223456978,
        'resolveTime': 1545091200000,
        'openTimestamp': 1544821632000,
        'iteration': 6,
        'bidIncrement': 100,
        'auctionId': 'AEDF0E58-0529-4814-9E96-458A7BCB0B63',
        'originVehicleId': '411341851',
        'vehicleId': '63BB07E7-6416-4081-A02C-BA6BD3B0CC9E',
        'startPrice': 42900,
        'reservePrice': 42900,
        'buyNowPrice': 43100,
        'auctionStatus': null,
        'viewAccessGroupList': ['1', '312'],
        'bidAccessGroupList': ['1', '312'],
        'bestOfferAccessGroupList': ['1', '312'],
        'buyAccessGroupList': ['1', '312'],
        'buyDisappearLimitType': null,
        'buyDisappearLimit': null,
        'isActive': true,
        'bidCount': 0,
        'bidderCount': 0,
        'userHasBid': false,
        'winningBidAmount': null,
        'winningBidMaxAmount': null,
        'winningBidLoginId': null,
        'winningBidLoginName': null,
        'winningBidOrganizationName': null,
        'bestOfferCount': 0,
        'previewStartTime': null,
        'previewType': null,
        'ifBidPrice': null,
        'ifBidDeclinedByWinningBidder': false,
        'backBiddingEnabled': true,
        'ifBidActionType': null,
        'isPriceFloor': false,
        'showRepairEstimates': false,
        'showLaborEstimates': false,
        'userLatestBestOffer': null,
        'userLatestBid': null,
        'canBuy': true,
        'canBid': true,
        'canBestOffer': true,
        'allowBuy': true,
        'allowBid': true,
        'allowBestOffer': true,
        'allowProxyAutoBid': false,
        'allowDeclineIfBid': false,
        'isPreviewPeriod': false,
        'sellerReserveMatchBid': false,
        'isPriceAdjusted': false,
        'userIsWinning': false,
        'allowToRemoveWatchlist': true,
        'showListingCategory': true,
        'showDB': true,
        'isOpenReserveFlag': true,
        'openReserveMessage': 'The opening bid equals the reserve price set by the seller',
        'showIconFlag': false,
        'showReserveMetFlag': false,
        'showReserveNotMetFlag': false,
        'iconMessage': null,
        'isReserveMetMessage': 'No Reserve',
        'noReserveFlag': true,
        'reserveMetFlag': false,
        'reserveNotMetFlag': false,
        'remainingAuctionEndTime': 22160227,
        'previewRemainingStartTime': 0,
        'auctionRemainingEndTime': 22160227,
        'auctionRemainingStartTime': 0,
        'currentTimeInUTC': 1545058239773
    }
};

export const mockDBBidBuyResponseWithBid = {
    'dealerBlockAuction': {
        'auctionStartTime': 2234567,
        'auctionEndTime': 223456978,
        'resolveTime': 1545091200000,
        'openTimestamp': 1544821632000,
        'iteration': 6,
        'bidIncrement': 100,
        'auctionId': 'AEDF0E58-0529-4814-9E96-458A7BCB0B63',
        'originVehicleId': '411341851',
        'vehicleId': '63BB07E7-6416-4081-A02C-BA6BD3B0CC9E',
        'startPrice': 42900,
        'reservePrice': 42900,
        'buyNowPrice': 43100,
        'auctionStatus': null,
        'viewAccessGroupList': ['1', '312'],
        'bidAccessGroupList': ['1', '312'],
        'bestOfferAccessGroupList': ['1', '312'],
        'buyAccessGroupList': ['1', '312'],
        'buyDisappearLimitType': null,
        'buyDisappearLimit': null,
        'isActive': true,
        'bidCount': 0,
        'bidderCount': 0,
        'userHasBid': false,
        'winningBidAmount': 43000,
        'winningBidMaxAmount': 43000,
        'winningBidLoginId': 'loginId',
        'winningBidLoginName': 'loginName',
        'winningBidOrganizationName': 'orgName',
        'bestOfferCount': 0,
        'previewStartTime': null,
        'previewType': null,
        'ifBidPrice': null,
        'ifBidDeclinedByWinningBidder': false,
        'backBiddingEnabled': true,
        'ifBidActionType': null,
        'isPriceFloor': false,
        'showRepairEstimates': false,
        'showLaborEstimates': false,
        'userLatestBestOffer': null,
        'userLatestBid': null,
        'canBuy': true,
        'canBid': true,
        'canBestOffer': true,
        'allowBuy': true,
        'allowBid': true,
        'allowBestOffer': true,
        'allowProxyAutoBid': false,
        'allowDeclineIfBid': false,
        'isPreviewPeriod': false,
        'sellerReserveMatchBid': false,
        'isPriceAdjusted': false,
        'userIsWinning': false,
        'allowToRemoveWatchlist': true,
        'showListingCategory': true,
        'showDB': true,
        'isOpenReserveFlag': true,
        'openReserveMessage': 'The opening bid equals the reserve price set by the seller',
        'showIconFlag': false,
        'showReserveMetFlag': false,
        'showReserveNotMetFlag': false,
        'iconMessage': null,
        'isReserveMetMessage': 'No Reserve',
        'noReserveFlag': true,
        'reserveMetFlag': false,
        'reserveNotMetFlag': false,
        'remainingAuctionEndTime': 22160227,
        'previewRemainingStartTime': 0,
        'auctionRemainingEndTime': 22160227,
        'auctionRemainingStartTime': 0,
        'currentTimeInUTC': 1545058239773
    }
};

export const mockDBBuyOnlyResponse = {
    'dealerBlockAuction': {
        'auctionStartTime': 2234567,
        'auctionEndTime': 223456978,
        'resolveTime': 1545091200000,
        'openTimestamp': 1544821632000,
        'iteration': 6,
        'bidIncrement': 100,
        'auctionId': 'AEDF0E58-0529-4814-9E96-458A7BCB0B63',
        'originVehicleId': '411341851',
        'vehicleId': '63BB07E7-6416-4081-A02C-BA6BD3B0CC9E',
        'startPrice': 42900,
        'reservePrice': 42900,
        'buyNowPrice': 43100,
        'auctionStatus': null,
        'viewAccessGroupList': ['1', '312'],
        'bidAccessGroupList': ['1', '312'],
        'bestOfferAccessGroupList': ['1', '312'],
        'buyAccessGroupList': ['1', '312'],
        'buyDisappearLimitType': null,
        'buyDisappearLimit': null,
        'isActive': true,
        'bidCount': 0,
        'bidderCount': 0,
        'userHasBid': false,
        'winningBidAmount': null,
        'winningBidMaxAmount': null,
        'winningBidLoginId': null,
        'winningBidLoginName': null,
        'winningBidOrganizationName': null,
        'bestOfferCount': 0,
        'previewStartTime': null,
        'previewType': null,
        'ifBidPrice': null,
        'ifBidDeclinedByWinningBidder': false,
        'backBiddingEnabled': true,
        'ifBidActionType': null,
        'isPriceFloor': false,
        'showRepairEstimates': false,
        'showLaborEstimates': false,
        'userLatestBestOffer': null,
        'userLatestBid': null,
        'canBuy': true,
        'canBid': false,
        'canBestOffer': true,
        'allowBuy': true,
        'allowBid': false,
        'allowBestOffer': true,
        'allowProxyAutoBid': false,
        'allowDeclineIfBid': false,
        'isPreviewPeriod': false,
        'sellerReserveMatchBid': false,
        'isPriceAdjusted': false,
        'userIsWinning': false,
        'allowToRemoveWatchlist': true,
        'showListingCategory': true,
        'showDB': true,
        'isOpenReserveFlag': true,
        'openReserveMessage': 'The opening bid equals the reserve price set by the seller',
        'showIconFlag': false,
        'showReserveMetFlag': false,
        'showReserveNotMetFlag': false,
        'iconMessage': null,
        'isReserveMetMessage': 'No Reserve',
        'noReserveFlag': true,
        'reserveMetFlag': false,
        'reserveNotMetFlag': false,
        'remainingAuctionEndTime': 22160227,
        'previewRemainingStartTime': 0,
        'auctionRemainingEndTime': 22160227,
        'auctionRemainingStartTime': 0,
        'currentTimeInUTC': 1545058239773
    }
};


export const mockVehicleDealerBlockBidBuyNoBid = {
    buyNowPrice: mockDBBidBuyResponseNoBid.dealerBlockAuction.buyNowPrice,
    canBuy: mockDBBidBuyResponseNoBid.dealerBlockAuction.canBuy,
    allowBuy: mockDBBidBuyResponseNoBid.dealerBlockAuction.allowBuy,
    canBid: mockDBBidBuyResponseNoBid.dealerBlockAuction.canBid,
    allowBid: mockDBBidBuyResponseNoBid.dealerBlockAuction.allowBid,
    startPrice: mockDBBidBuyResponseNoBid.dealerBlockAuction.startPrice,
    winningBidAmount: mockDBBidBuyResponseNoBid.dealerBlockAuction.winningBidAmount,
    shownPrice: mockDBBidBuyResponseNoBid.dealerBlockAuction.startPrice
};

export const mockVehicleDealerBlockBidBuyWithBid = {
    buyNowPrice: mockDBBidBuyResponseWithBid.dealerBlockAuction.buyNowPrice,
    canBuy: mockDBBidBuyResponseWithBid.dealerBlockAuction.canBuy,
    allowBuy: mockDBBidBuyResponseWithBid.dealerBlockAuction.allowBuy,
    canBid: mockDBBidBuyResponseWithBid.dealerBlockAuction.canBid,
    allowBid: mockDBBidBuyResponseWithBid.dealerBlockAuction.allowBid,
    startPrice: mockDBBidBuyResponseWithBid.dealerBlockAuction.startPrice,
    winningBidAmount: mockDBBidBuyResponseWithBid.dealerBlockAuction.winningBidAmount,
    shownPrice: mockDBBidBuyResponseWithBid.dealerBlockAuction.winningBidAmount
};

export const mockVehicleDealerBlockBuyOnly = {
    buyNowPrice: mockDBBuyOnlyResponse.dealerBlockAuction.buyNowPrice,
    canBuy: mockDBBuyOnlyResponse.dealerBlockAuction.canBuy,
    allowBuy: mockDBBuyOnlyResponse.dealerBlockAuction.allowBuy,
    canBid: mockDBBuyOnlyResponse.dealerBlockAuction.canBid,
    allowBid: mockDBBuyOnlyResponse.dealerBlockAuction.allowBid,
    startPrice: mockDBBuyOnlyResponse.dealerBlockAuction.startPrice,
    winningBidAmount: mockDBBuyOnlyResponse.dealerBlockAuction.winningBidAmount,
    shownPrice: mockDBBuyOnlyResponse.dealerBlockAuction.buyNowPrice
};



export const mockProdDBResponse = {
    'dealerBlockAuction': {
        'auctionStartTime': 12365456,
        'auctionEndTime': 789789978,
        'resolveTime': 1545091200000,
        'openTimestamp': 1544821632000,
        'iteration': 6,
        'bidIncrement': 100,
        'auctionId': 'AEDF0E58-0529-4814-9E96-458A7BCB0B65',
        'originVehicleId': '411341871',
        'vehicleId': '63BB07E7-6416-4081-A02C-BA6BD3B0CC9F',
        'startPrice': 42900,
        'reservePrice': 42900,
        'buyNowPrice': 43100,
        'auctionStatus': null,
        'viewAccessGroupList': ['1', '312'],
        'bidAccessGroupList': ['1', '312'],
        'bestOfferAccessGroupList': ['1', '312'],
        'buyAccessGroupList': ['1', '312'],
        'buyDisappearLimitType': 'Fixed Amount',
        'buyDisappearLimit': 500,
        'isActive': true,
        'bidCount': 0,
        'bidderCount': 0,
        'userHasBid': false,
        'winningBidAmount': null,
        'winningBidMaxAmount': null,
        'winningBidLoginId': null,
        'winningBidLoginName': null,
        'winningBidOrganizationName': null,
        'bestOfferCount': 0,
        'previewStartTime': null,
        'previewType': null,
        'ifBidPrice': null,
        'ifBidDeclinedByWinningBidder': false,
        'backBiddingEnabled': true,
        'ifBidActionType': null,
        'isPriceFloor': false,
        'showRepairEstimates': false,
        'showLaborEstimates': false,
        'userLatestBestOffer': null,
        'userLatestBid': null,
        'canBuy': true,
        'canBid': true,
        'canBestOffer': true,
        'allowBuy': true,
        'allowBid': true,
        'allowBestOffer': true,
        'allowProxyAutoBid': false,
        'allowDeclineIfBid': false,
        'isPreviewPeriod': false,
        'sellerReserveMatchBid': false,
        'isPriceAdjusted': false,
        'userIsWinning': false,
        'allowToRemoveWatchlist': true,
        'showListingCategory': true,
        'showDB': true,
        'isOpenReserveFlag': true,
        'openReserveMessage': 'The opening bid equals the reserve price set by the seller',
        'showIconFlag': false,
        'showReserveMetFlag': false,
        'showReserveNotMetFlag': false,
        'iconMessage': null,
        'isReserveMetMessage': 'No Reserve',
        'noReserveFlag': true,
        'reserveMetFlag': false,
        'reserveNotMetFlag': false,
        'remainingAuctionEndTime': 22160227,
        'previewRemainingStartTime': 0,
        'auctionRemainingEndTime': 22160227,
        'auctionRemainingStartTime': 0,
        'currentTimeInUTC': 1545058239773
    }
};
